services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
    laravel.worker:
        image: sail-8.2/app
        command: php artisan queue:work
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-baknusattend}'
            MYSQL_USER: '${DB_USERNAME:-sail}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        restart: unless-stopped
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-ppassword'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        restart: unless-stopped
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mosquitto:
        image: 'eclipse-mosquitto:latest'
        ports:
            - '${FORWARD_MQTT_PORT:-1883}:1883'
            - '${FORWARD_MQTT_WS_PORT:-9001}:9001'
        volumes:
            - './mosquitto/config:/mosquitto/config'
            - 'sail-mosquitto-data:/mosquitto/data'
            - 'sail-mosquitto-log:/mosquitto/log'
        networks:
            - sail
        restart: unless-stopped
    compreface-postgres-db:
        image: exadel/compreface-postgres-db:1.2.0
        restart: unless-stopped
        container_name: "compreface-postgres-db"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=compreface
        volumes:
            - compreface-postgres-data:/var/lib/postgresql/data
        networks:
            - sail

    compreface-admin:
        restart: unless-stopped
        image: exadel/compreface-admin:1.2.0
        container_name: "compreface-admin"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/compreface
            - SPRING_PROFILES_ACTIVE=dev
            - MAX_FILE_SIZE=5MB
            - MAX_REQUEST_SIZE=5242880B
        depends_on:
            - compreface-postgres-db
            - compreface-api
        networks:
            - sail

    compreface-api:
        restart: unless-stopped
        image: exadel/compreface-api:1.2.0
        container_name: "compreface-api"
        depends_on:
            - compreface-postgres-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/compreface
            - SPRING_PROFILES_ACTIVE=dev
            - SAVE_IMAGES_TO_DB=true
            - MAX_FILE_SIZE=5MB
            - MAX_REQUEST_SIZE=5242880B
            - CONNECTION_TIMEOUT=10000
            - READ_TIMEOUT=60000
        networks:
            - sail

    compreface-ui:
        restart: unless-stopped
        image: exadel/compreface-fe:1.2.0
        container_name: "compreface-ui"
        ports:
            - "8000:80"
        depends_on:
            - compreface-api
            - compreface-admin
        environment:
            - CLIENT_MAX_BODY_SIZE=5242880B
            - PROXY_READ_TIMEOUT=60000ms
            - PROXY_CONNECT_TIMEOUT=10000ms
        networks:
            - sail

    compreface-core:
        restart: unless-stopped
        image: exadel/compreface-core:1.2.0
        container_name: "compreface-core"
        environment:
            - ML_PORT=3000
            - IMG_LENGTH_LIMIT=5242880
            - UWSGI_PROCESSES=2
            - UWSGI_THREADS=1
        healthcheck:
            test: curl --fail http://localhost:3000/healthcheck || exit 1
            interval: 10s
            retries: 0
            start_period: 0s
            timeout: 1s
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-mosquitto-data:
        driver: local
    sail-mosquitto-log:
        driver: local
    compreface-postgres-data:
        driver: local
